CREATE TABLE doctor (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    extra_shifts INT NOT NULL DEFAULT 0,
    color VARCHAR(7) NOT NULL DEFAULT '#667eea'
);
